### ISSUE TITLE
Add notes to session.

### ISSUE THREAD

**Issue by jerold** [davidmarne/retro#10]
Initiate adding a note to an item via some button in the item. This button allows the user to create a new note, or select from an existing note (tagging that note to the item).

**Comment by jerold** [comment]
From https://github.com/davidmarne/retro/issues/37:

> Can you include a long form text space so I can write down action items, and assign them to team members? Bonus points if it emails those people later to remind them.
@omgitsjessie

**Comment by SpencerCornish** [comment]
Looks to be merged @jerold ?

**Comment by jerold** [comment]
Yup :) Thanks @SpencerCornish
