### ISSUE TITLE
Sort session results by +1's

### ISSUE THREAD

**Issue by philiplegros-wf** [davidmarne/retro#54]
Generally we like to use +1's to represent how many people want to talk about it. So the more popular issues generally get talked about first, so that we can prioritize the conversation. Might be good to have this as an option for the app.

**Comment by davidmarne** [comment]
dupe https://github.com/davidmarne/retro/issues/30

**Comment by davidmarne** [comment]
thanks for trying it out phil! I'ld say this is one of the next issues we will tackle
