### ISSUE TITLE
Add voting to items

### ISSUE THREAD

**Issue by jerold** [davidmarne/retro#9]
Users should have the ability to vote for an item. Item objects have a supporterUids map, to which we should add the supporting user's uid when they press a "vote for" button on the item element. Map has the keys == userUid, and I think value == some int value. Start with a simple 1 value.

In the future we may want to let users vote down, or have levels of vote enthusiasm... but a 1 is good for now.

**Comment by SpencerCornish** [comment]
I'm going to mess with this later today. No guarantees but I'll see what I can do!
